# Description: Configuration file for the application

##################
# EXAMPLE CONFIG #
##################

train_path: "../train.npy"
val_path: "../val.npy"
test_path: "../test.npy"
model_params:
  window_size: 120
  batch_size: 64
  static_real_cols: null
  static_cat_cols: ["treatment", "field_id"]
  historical_real_cols: [
    'vmc_10', 
    'vmc_70', 
    'avg_temp', 
    'wind_speed', 
    'wind_dir', 
    'radiation', 
    'precipitation', 
    'dew_point_kpa', 
    'irr_mm'
    ]
  historical_cat_cols: ["month", "hour"]
  known_cat_cols: ["month", "hour"]
  known_real_cols: ["precipitation", "avg_temp"]
  cut_off_train: "2010-06"
  cut_off_val: "2010-09-15"
  date_col: "datetime"
  target_col: ["vmc_10", "avg_swp"]
  group_col: "composite_group_id"
  time_col: "time_idx"
  mixed_only: false
  time_gap: 12
  dropout_rate: 0.1
  num_heads: 2
  hidden_layer_size: 16
  output_size: 3
  quantiles: [0.05, 0.5, 0.95]
train_params:
  epochs: 200